### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Emilef22** [daweizhangau/esphome_uni_trend_sound_meter#5]
Hello,
I already have the component install on another esp32 and it works great! Now i'm trying to install it on another esp32 ans i get this code:

INFO Reading configuration /config/esphome/store-toilette-soundmeter.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing store-toilette-soundmeter (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
Library Manager: Installing Hash
INFO Installing Hash
Library Manager: Installing ESP8266WiFi
INFO Installing ESP8266WiFi
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 1.0
|-- FS @ 1.0
|-- Update @ 1.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 1.1.0
|-- ESPmDNS @ 1.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
|-- ArduinoJson @ 6.18.5
Compiling /data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp.o
Compiling /data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/src/main.cpp.o
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp: In member function 'virtual void esphome::uni_trend_sound_meter::UnitTrendSoundMeter::gattc_event_handler(esp_gattc_cb_event_t, esp_gatt_if_t, esp_ble_gattc_cb_param_t*)':
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:73:63: error: 'class esphome::ble_client::BLEClient' has no member named 'gattc_if'
             esp_ble_gattc_register_for_notify(this->parent()->gattc_if, this->parent()->remote_bda, this->output_handle_);
                                                               ^
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:73:89: error: 'class esphome::ble_client::BLEClient' has no member named 'remote_bda'
             esp_ble_gattc_register_for_notify(this->parent()->gattc_if, this->parent()->remote_bda, this->output_handle_);
                                                                                         ^
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:83:52: error: 'class esphome::ble_client::BLEClient' has no member named 'conn_id'
       if (param->notify.conn_id != this->parent()->conn_id || param->notify.handle != this->output_handle_)
                                                    ^
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp: In member function 'virtual void esphome::uni_trend_sound_meter::UnitTrendSoundMeter::update()':
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:137:21: error: 'class esphome::ble_client::BLEClient' has no member named 'gattc_if'
     this->parent()->gattc_if, 
                     ^
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:138:21: error: 'class esphome::ble_client::BLEClient' has no member named 'conn_id'
     this->parent()->conn_id, 
                     ^
*** [/data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp.o] Error 1
========================== [FAILED] Took 6.83 seconds ==========================

Can you please help me?
Thanks a lot!

**Comment by daweizhangau** [comment]
@Emilef22 ESP8266 doesn't support `esp32_ble_tracker`, you need to use a ESP32.

**Comment by Emilef22** [comment]
I can assure you that it is not on a 8266 and my Ble tracker works well.

**Comment by daweizhangau** [comment]
@Emilef22  I formatted your code, but just removing the `ap` section, which doesn't work for me. I cannot reproduce the issue you mentioned. 

```yaml
esphome:
  name: store-toilette-soundmeter

esp32:
  board: esp32dev
  framework:
    type: arduino
logger:

api:
  encryption:
    key: "4wL+Lp/nu3N9GLdCHrTrCsNR8eM6Gt0n8K3TKRomGZ8="

ota:
  password: "ba87bfb8788005a4374bb739a837bfb9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# ap:
#   ssid: "Store-Toilette-Soundmeter"
#   password: "AHqk7QPzi7Tv"

captive_portal:

external_components:
    source: github://daweizhangau/esphome_uni_trend_sound_meter@v1.0.0

esp32_ble_tracker:

uni_trend_sound_meter:
  name: "Sound Level"
  icon: 'mdi:microphone'
  unit_of_measurement: 'dBA'
  ble_client_id: sound_meter_ble_client
  update_interval: 1s
  
web_server:
  port: 80

ble_client:
  mac_address: E8:D0:3C:51:89:66
  id: sound_meter_ble_client

```


```text
Linking /data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/firmware.elf
RAM:   [==        ]  16.4% (used 53708 bytes from 327680 bytes)
Flash: [========= ]  88.5% (used 1624082 bytes from 1835008 bytes)
Building /data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/firmware.bin
esp32_create_combined_bin(["/data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/firmware.bin"], ["/data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/firmware.elf"])
Wrote 0x19c880 bytes to file /data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/firmware-factory.bin, ready to flash to offset 0x0
======================== [SUCCESS] Took 217.96 seconds ========================
INFO Successfully compiled program.
```

**Comment by Emilef22** [comment]
Okay very strange, I have the 2022.10.0 version, if you can try with that version too it would be very appreciated. Thanks!

**Comment by Emilef22** [comment]
Hi again!
For me, it still only works with 2022.9.3 or before esphome addon MAJ
Thanks again!

**Comment by daweizhangau** [comment]
@Emilef22 Are you seeing an error link this?
https://community.home-assistant.io/t/esphome-could-not-find-package-json/499026

**Comment by Emilef22** [comment]
No, when I'am trying to update i get this error:

**Comment by Emilef22** [comment]
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp: In member function 'virtual void esphome::uni_trend_sound_meter::UnitTrendSoundMeter::gattc_event_handler(esp_gattc_cb_event_t, esp_gatt_if_t, esp_ble_gattc_cb_param_t*)':
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:73:63: error: 'class esphome::ble_client::BLEClient' has no member named 'gattc_if'; did you mean 'gattc_if_'?
             esp_ble_gattc_register_for_notify(this->parent()->gattc_if, this->parent()->remote_bda, this->output_handle_);
                                                               ^~~~~~~~
                                                               gattc_if_
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:73:89: error: 'class esphome::ble_client::BLEClient' has no member named 'remote_bda'; did you mean 'remote_bda_'?
             esp_ble_gattc_register_for_notify(this->parent()->gattc_if, this->parent()->remote_bda, this->output_handle_);
                                                                                         ^~~~~~~~~~
                                                                                         remote_bda_
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:83:52: error: 'class esphome::ble_client::BLEClient' has no member named 'conn_id'; did you mean 'conn_id_'?
       if (param->notify.conn_id != this->parent()->conn_id || param->notify.handle != this->output_handle_)
                                                    ^~~~~~~
                                                    conn_id_
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp: In member function 'virtual void esphome::uni_trend_sound_meter::UnitTrendSoundMeter::update()':
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:137:21: error: 'class esphome::ble_client::BLEClient' has no member named 'gattc_if'; did you mean 'gattc_if_'?
     this->parent()->gattc_if,
                     ^~~~~~~~
                     gattc_if_
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:138:21: error: 'class esphome::ble_client::BLEClient' has no member named 'conn_id'; did you mean 'conn_id_'?
     this->parent()->conn_id,
                     ^~~~~~~
                     conn_id_
*** [/data/soundmeter/.pioenvs/soundmeter/src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp.o] Error 1
========================= [FAILED] Took 23.06 seconds =========================



Thanks a lot!

**Comment by daweizhangau** [comment]
It seems like a compatibility issue since upgrade. And it tells you how to update the code. Maybe in a separate branch or fork the repo. Do you mind trying it?

**Comment by Emilef22** [comment]
Yes I can try, I'm not skilled at all but I have to add a _ at those 5 lines if I understand?

**Comment by daweizhangau** [comment]
Yes, please try that.

**Comment by Emilef22** [comment]
After the change I get this one: 

src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp: In member function 'virtual void esphome::uni_trend_sound_meter::UnitTrendSoundMeter::gattc_event_handler(esp_gattc_cb_event_t, esp_gatt_if_t, esp_ble_gattc_cb_param_t*)':
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:73:63: error: 'int esphome::esp32_ble_client::BLEClientBase::gattc_if_' is protected within this context
             esp_ble_gattc_register_for_notify(this->parent()->gattc_if_, this->parent()->remote_bda_, this->output_handle_);
                                                               ^~~~~~~~~
In file included from src/esphome/components/ble_client/ble_client.h:3,
                 from src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.h:4,
                 from src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:1:
src/esphome/components/esp32_ble_client/ble_client_base.h:80:7: note: declared protected here
   int gattc_if_;
       ^~~~~~~~~
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:73:63: note: field 'int esphome::esp32_ble_client::BLEClientBase::gattc_if_' can be accessed via 'int esphome::esp32_ble_client::BLEClientBase::get_gattc_if() const'
             esp_ble_gattc_register_for_notify(this->parent()->gattc_if_, this->parent()->remote_bda_, this->output_handle_);
                                                               ^~~~~~~~~
                                                               get_gattc_if()
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:73:90: error: 'uint8_t esphome::esp32_ble_client::BLEClientBase::remote_bda_ [6]' is protected within this context
             esp_ble_gattc_register_for_notify(this->parent()->gattc_if_, this->parent()->remote_bda_, this->output_handle_);
                                                                                          ^~~~~~~~~~~
In file included from src/esphome/components/ble_client/ble_client.h:3,
                 from src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.h:4,
                 from src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:1:
src/esphome/components/esp32_ble_client/ble_client_base.h:81:17: note: declared protected here
   esp_bd_addr_t remote_bda_;
                 ^~~~~~~~~~~
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:83:52: error: 'uint16_t esphome::esp32_ble_client::BLEClientBase::conn_id_' is protected within this context
       if (param->notify.conn_id != this->parent()->conn_id_ || param->notify.handle != this->output_handle_)
                                                    ^~~~~~~~
In file included from src/esphome/components/ble_client/ble_client.h:3,
                 from src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.h:4,
                 from src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:1:
src/esphome/components/esp32_ble_client/ble_client_base.h:83:27: note: declared protected here
   uint16_t conn_id_{0xFFFF};
                           ^
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:83:52: note: field 'uint16_t esphome::esp32_ble_client::BLEClientBase::conn_id_' can be accessed via 'uint16_t esphome::esp32_ble_client::BLEClientBase::get_conn_id() const'
       if (param->notify.conn_id != this->parent()->conn_id_ || param->notify.handle != this->output_handle_)
                                                    ^~~~~~~~
                                                    get_conn_id()
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp: In member function 'virtual void esphome::uni_trend_sound_meter::UnitTrendSoundMeter::update()':
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:137:21: error: 'int esphome::esp32_ble_client::BLEClientBase::gattc_if_' is protected within this context
     this->parent()->gattc_if_,
                     ^~~~~~~~~
In file included from src/esphome/components/ble_client/ble_client.h:3,
                 from src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.h:4,
                 from src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:1:
src/esphome/components/esp32_ble_client/ble_client_base.h:80:7: note: declared protected here
   int gattc_if_;
       ^~~~~~~~~
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:137:21: note: field 'int esphome::esp32_ble_client::BLEClientBase::gattc_if_' can be accessed via 'int esphome::esp32_ble_client::BLEClientBase::get_gattc_if() const'
     this->parent()->gattc_if_,
                     ^~~~~~~~~
                     get_gattc_if()
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:138:21: error: 'uint16_t esphome::esp32_ble_client::BLEClientBase::conn_id_' is protected within this context
     this->parent()->conn_id_,
                     ^~~~~~~~
In file included from src/esphome/components/ble_client/ble_client.h:3,
                 from src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.h:4,
                 from src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:1:
src/esphome/components/esp32_ble_client/ble_client_base.h:83:27: note: declared protected here
   uint16_t conn_id_{0xFFFF};
                           ^
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:138:21: note: field 'uint16_t esphome::esp32_ble_client::BLEClientBase::conn_id_' can be accessed via 'uint16_t esphome::esp32_ble_client::BLEClientBase::get_conn_id() const'
     this->parent()->conn_id_,
                     ^~~~~~~~
                     get_conn_id()
*** [/data/soundmeter/.pioenvs/soundmeter/src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp.o] Error 1
========================== [FAILED] Took 4.41 seconds ==========================

**Comment by Emilef22** [comment]
Hello, have you had the chance to try it on a recent esphome update? Still got the same error. Thanks

**Comment by fragande** [comment]
> Hello, have you had the chance to try it on a recent esphome update? Still get the same error. Thanks

I'm getting the same error trying to update the YAML on the ESP32 I use for this component. I've "solved" it by keeping an older version of ESPHome (2022.9.2 is the latest that works) installed in a Python virtual environment on my PC and use that for OTA updates.

**Comment by Emilef22** [comment]
Okay good, I'm doing exactly the same. Nice to know i'm not the only one. Maybe it can be fixed? @daweizhangau :)

**Comment by mamoit** [comment]
I had the same problem.
Got it to build by using the `main` branch instead of `v1.0.0`.
``` yaml
external_components:
    source: github://daweizhangau/esphome_uni_trend_sound_meter@main
```

**Comment by Emilef22** [comment]
Nice! thanks you!!

**Comment by mamoit** [comment]
Sorry it took 9 months for you to get a solution, I just started using it :slightly_smiling_face:
@daweizhangau do you want me to make a PR to update the `README.md` or would you rather keep pinned to `v1.0.0`?

**Comment by mamoit** [comment]
@Emilef22 doc updated :slightly_smiling_face:
