### PR TITLE
Fix build with ESPHome 2025.12: address_str() API change

### PR DESCRIPTION
**Pull request by tsgoff**
### Summary

This PR fixes a build error with ESPHome >= 2025.12 caused by an API change in
`BLEClient::address_str()`.

ESPHome changed `address_str()` from returning `std::string` to `const char*`.
The current code still calls `.c_str()`, which results in a compilation error.

### Changes

- Remove unnecessary `.c_str()` call on `address_str()`
- No functional behavior change, logging output remains identical

### Before

```cpp
ESP_LOGCONFIG(TAG, "  MAC address        : %s", this->parent()->address_str().c_str());

### CODE REVIEW

**Comment by CLARENNE-Q** [comment]
Thanks a lot [tsgoff](https://github.com/tsgoff)

 it's work fine, in my case, I use it like it:

```
external_components:
  - source: github://tsgoff/esphome_uni_trend_sound_meter@patch-1
```

**Comment by CLARENNE-Q** [comment]
@daweizhangau     Can you approve this PR ?

**Comment by shtrom** [comment]
Tested and works too. Thanks @tsgoff

**Review by daweizhangau — APPROVED** [review]
Reproduced and tested on `ghcr.io/esphome/esphome:2026.1.5`.
@tsgoff Thank you for raising the PR!
@shtrom Thank you for testing!

**Comment by tsgoff** [comment]
Proposal for an automated test in GitHub Actions:

```yaml
name: ESPHome Build Test from MD
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Extract YAML from how_to_flash.md
        run: |
          # Extrahiert den Code-Block zwischen ```yaml und ```
          sed -n '/^```yaml/,/^```/p' how_to_flash.md | sed '1d;$d' > soundmeter.yaml
          echo "Extrahierte Datei:"
          cat soundmeter.yaml
      - name: Create dummy secrets.yaml
        run: |
          echo "wifi_ssid: 'Dummy-SSID'" > secrets.yaml
          echo "wifi_password: 'Dummy-Password'" >> secrets.yaml
          echo "ota_password: 'Dummy'" >> secrets.yaml
          echo "api_encryption_key: 'MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI='" >> secrets.yaml
      - name: Build ESPHome Firmware
        uses: esphome/build-action@v6
        with:
          yaml-file: "soundmeter.yaml"
          version: latest
```
